config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    #byebug
    @todo = Todo.new(params.permit(:task,:completed))
      if @todo.save
        redirect_to todos_path
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    if @todo.update(todo_params)
      redirect_to todos_path
       
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
  
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:task, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" align="center">
    <%= yield %>

    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="form-row align-item-center">
<div class="container" align="center">
<div class="row">
<div class="col-md-4">


<%= form_with(model: todo) do |form| %>
  <div class="field">
    <h><%= form.label :Task %></h1>
    <%= form.text_field :task,class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
<% end %>

</div>
</div>

</div>


</div>

app/views/todos/edit.html.erb
<div class="jumbotron" align=center> 
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>
</div>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p><br><br><br>


<table class="table table-bordered table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>TASK</th>
      <th>ACTION</th>
      <th>ACTION</th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <% if todo.completed %>
            <tr class="table-info">
              <td><strike><%= todo.task %></strike></td>
              <td><%= link_to 'Edit', edit_todo_path(todo),class: 'btn btn-outline-primary disabled' %></td>
              <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-outline-danger' %></td>
            </tr>
      <% else %>
              <tr class="table-danger">
              <td><%= todo.task %></td>
              <td><%= link_to 'Edit', edit_todo_path(todo),class: 'btn btn-outline-primary' %></td>
              <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-outline-danger' %></td>
              </tr>
            <% end %>  

    <% end %>
  </body>
</table>

<br>
<div class="jumbotron" style="background-color:#d8f750">
<%= render 'form', todo: @todo %>
</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @todo.task %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>